[package]
name = "sms_scraper"
version = "0.1.0"
edition = "2021"
description = "Rust-based event data scraper for Seattle Music Scene"

[dependencies]
# Async runtime and HTTP client
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Date and time handling
chrono = { version = "0.4", features = ["serde"] }

# HTML parsing for crawlers
scraper = "0.19"
select = "0.6"

# Error handling and logging
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "fmt", "local-time"] }
tracing-appender = "0.2"

# Environment variables
dotenv = "0.15"

# Command line interface
clap = { version = "4.0", features = ["derive"] }

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# Async traits
async-trait = "0.1"
