services:
  scraper:
    build: .
    image: sms-scraper:latest
    container_name: sms_scraper
    ports:
      - "8080:8080"
      - "9898:9898"
    environment:
      - SMS_METRICS_PORT=9898
      - SMS_PUSHGATEWAY_URL=http://pushgateway:9091
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=5GB
    ports:
      - "9090:9090"
    depends_on:
      scraper:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: ["observability"]
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - scraper

volumes:
  prometheus_data:
