services:
  scraper:
    build: .
    image: sms-scraper:latest
    container_name: sms_scraper
    ports:
      - "8080:8080"   # GraphQL API
      - "9464:9464"   # Prometheus metrics endpoint
    environment:
      - PROMETHEUS_ADDR=0.0.0.0:9464
      - SMS_PUSHGATEWAY_URL=http://pushgateway:9091
      - RUST_LOG=info
      - LIBSQL_URL=${LIBSQL_URL}
      - LIBSQL_AUTH_TOKEN=${LIBSQL_AUTH_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - ./data:/app/data    # Persist scraper data
    restart: unless-stopped
    command: ["/usr/local/bin/sms_scraper", "server", "--port", "8080"]

  web:
    build: .
    image: sms-scraper:latest
    container_name: sms_web
    depends_on:
      scraper:
        condition: service_healthy
    environment:
      - PORT=3001
      - GRAPHQL_URL=http://scraper:8080/graphql
    ports:
      - "3001:3001"
    command: ["/usr/local/bin/web-server"]

  # One-off ingester job, run with: docker compose run --rm ingester
  ingester:
    image: sms-scraper:latest
    profiles: ["disabled"]
    environment:
      - SMS_PUSHGATEWAY_URL=http://pushgateway:9091
      - PROMETHEUS_ADDR=0.0.0.0:9898  # Metrics will be scraped from this port
      - RUST_LOG=info
    ports:
      - "9898:9898"  # Expose metrics port for scraping
    volumes:
      - ./data:/app/data
    depends_on:
      - pushgateway
    entrypoint: ["/usr/local/bin/sms_scraper"]
    command: ["ingester", "--apis", "blue_moon", "--bypass-cadence"]

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=5GB
    ports:
      - "9090:9090"
    depends_on:
      scraper:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - scraper

volumes:
  prometheus_data:
