global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sms_scraper_local'
    static_configs:
      # Standardize on 9464 for metrics
      - targets: ['host.docker.internal:9464']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
